### ISSUE TITLE
Date/time picker fields are missing

### ISSUE THREAD

**Issue by zelenij** [MangelMaxime/Fable.Form#27]
These are very common types of input and should be easy to add.  Best to have all three:

* Date + time together
* Date only
* Time only

**Comment by MangelMaxime** [comment]
They are common indeed, but their are no good libraries which is CSS framework agnostics for it yet.

So for now, if someone need to have support for it in their own project, they will need to write their own logic and view layer.

**Comment by MangelMaxime** [comment]
New fields support has been added, see https://github.com/MangelMaxime/Fable.Form/blob/main/packages/Fable.Form.Simple.Bulma/CHANGELOG.md#200---2021-10-15 for me info

I only added support to the field that were well supported by all the major browser as there is no polyfil to add support for them for others. For example, the `<input type="week">` has not been added because Firefox doesn't support it.

**Comment by zelenij** [comment]
Great, thanks, will check it out :)
