### ISSUE TITLE
Display error on submit

### ISSUE THREAD

**Issue by joahim** [MangelMaxime/Fable.Form#30]
When the user submits the form with one or more invalid fields, these fields are rendered with an error. For short forms this is how the user gets the feedback about the errors. However, if the form is long, such invalid fields, while still rendered correctly, may be above the fold and therefore there is no visual feedback to the user that the form is invalid.

Is there a mechanism to get the information about the form being invalid in the current implementation? Either similar to the `Success message` mechanism or some other way that would allow one to render the warning near the submit button or react in some other way.

**Comment by MangelMaxime** [comment]
In the `Fable.Form.Simple.Model` you have access to [`ErrorTracking`](https://github.com/MangelMaxime/Fable.Form/blob/4cb633cc1b5177632448f19cae70483dbdc8d914/packages/Fable.Form.Simple/Form.fs#L334) records.

It contains a boolean which is true if the error should be shown, and the list of the errored fields.

Fable.Form is build in a way where you can implements your own Form logic to matched the behaviour you want if needed.

https://mangelmaxime.github.io/Fable.Form/getting_started/use_what_you_need.html

This is difficult to have a single implementation which support all the uses cases of everyone, that's why it has been build with extensibility in mind.

**Comment by joahim** [comment]
I'm aware of the `ErrorTracking` but unfortunately that does not solve the problem of creating/receiving a message when the users clicks the submit button on the invalid form.

I now followed your advice and implemented custom logic in `FableForm.Simple` to support this behavior. It turned out to be quite simple and only involved adding an additional `OnSubmitError ` message parameter to the [`ViewConfig`](https://github.com/MangelMaxime/Fable.Form/blob/main/packages/Fable.Form.Simple/Form.fs#L342) type:

```
type ViewConfig<'Values, 'Msg> =
    {
        Dispatch : Dispatch<'Msg>
        OnChange : Model<'Values> -> 'Msg
        OnSubmitError : Model<'Values> -> 'Msg
        Action : string
        Validation : Validation
    }
```

and a bit of logic change to the [`custom`](https://github.com/MangelMaxime/Fable.Form/blob/main/packages/Fable.Form.Simple/Form.fs#L692) function:

```
| Result.Error _ ->
    if errorTracking.ShowAllErrors then
        viewConfig.OnSubmitError model |> Some

    else
        viewConfig.OnSubmitError
            { model with
                    ErrorTracking =
                        ErrorTracking
                            {| errorTracking with
                                ShowAllErrors = true
                            |}
            }
        |> Some
```

With this in place, one can react to `Submit` clicks for both valid and invalid form cases. I think this covers an important case when dealing with forms. If you agree I would be happy to prepare a PR.

Thanks again for this fantastic library!
