### ISSUE TITLE
Form plugins

### ISSUE THREAD

**Issue by LuisFX** [MangelMaxime/Fable.Form#37]
First off, the "Form.reactComponentField" is great! That said, it would be awesome to be able to expand the type of fields that Fable Forms can support through the use of plugins/extensions that we can all build/publish. Again, the reactComponentField works great, but a rigid contract will guarantee consistency.

We'll be trying to build a couple of them using reactComponentField for now:

listview:
<img width="552" alt="Screen Shot 2022-07-28 at 6 56 42 AM" src="https://user-images.githubusercontent.com/1130772/181523393-d75b812c-5a1e-4a7a-bf19-286868683fbb.png">

checkbox group:
<img width="227" alt="Screen Shot 2022-07-28 at 6 56 26 AM" src="https://user-images.githubusercontent.com/1130772/181523445-db8dcef4-4e04-46d6-b134-68afe3db4c12.png">

**Comment by LuisFX** [comment]
Maybe I'm missing something, because Fable.Form already has "rigid contracts" with these, right?

```fsharp
{
  Parser =
  Value =
  Update =
  Error = 
  Attributes =
}
```
and
```fsharp
{
  Dispatch =
  OnChange =
  Action =
  Validation =
}

**Comment by MangelMaxime** [comment]
What you are referring as "plugins" is actually related to the [following schema](https://mangelmaxime.github.io/Fable.Form/Fable.Form/use_what_you_need.html#what-should-i-use).

[Permalink](https://github.com/MangelMaxime/Fable.Form/blob/5ab323146f1a87d6608b63ec688c0021adf65de9/docs/assets/what_to_use_schema.svg)

If you answer the questions, you will see to the question "Does Fable.Form.Simple support all the fields you need?" the answer will be no.

And so, it will tell you to create your own Fable.Form.XXX packages to cover your needs. This is why, inside of your repo you have a custom version called `Fable.Form.Antidote`. This is because, it adds custom fields like Autocomplete.

---------

The component `Form.reactComponentField` that I added in your project is not something to use that much. 

This is actually something, I consider a hack because you can more or less do anything with it in an non typed way meaning that the compiler cannot really help you.

**Please do not use it, because it will not teach you how to write field the "correct" way**

-------

Adding new fields, is something that should be done by extending this DU:

https://github.com/MangelMaxime/Fable.Form/blob/5ab323146f1a87d6608b63ec688c0021adf65de9/packages/Fable.Form.Simple/Form.fs#L36-L44

So for example, if you want to have a list view component you would do:

```fs
    [<RequireQualifiedAccess; NoComparison; NoEquality>]
    type Field<'Values, 'Attributes> =
        | Text of TextType * TextField<'Values, 'Attributes>
        | Radio of RadioField<'Values>
        | Checkbox of CheckboxField<'Values>
        | Select of SelectField<'Values>
        | Group of FilledField<'Values, 'Attributes> list
        | Section of title : string * FilledField<'Values, 'Attributes> list
        | List of FormList.FormList<'Values, Field<'Values, 'Attributes>>
        | List of ListView.ListView<'Values, Field<'Values, 'Attributes>> // New field added here
```

and then follow the different compiler error.

In general, using `Radio` field as an example and searching for `Radio` everywhere in the package should give you a good idea of what needs to be done.

**Comment by LuisFX** [comment]
Thank you for this thorough answer. I'll definitely read through it and try to implement it the proper way!

While digging through it, I did find *flatCheckboxField* which seems to be implemented using the proper contract with Fable.Form, so I was already trying to replicate the behavior/contract of flatCheckboxField. I'll use that *and* the references for Radio, like you mentioned.
